BeginTrans
insert into [USER] (id,name,idClub,idResource,permission,password,comments) Values( '000','SUPERMAN J.','00','H007','2','toto','Gérant')
insert into [USER] (id,name,idClub,idResource,permission,password,comments) Values( '001','CHAMPION L.','00','H008','2','toto','Directeur')
insert into [USER] (id,name,idClub,idResource,permission,password,comments) Values( '011','RICHMAN P.','00','H022','1','toto','')
insert into [USER] (id,name,idClub,idResource,permission,password,comments) Values( '002','WILLIAM P.','01','H006','1','toto','Conseiller')
insert into [USER] (id,name,idClub,idResource,permission,password,comments) Values( '010','GERVET L.','01','H016','2','toto','Responsqble RH')
insert into [USER] (id,name,idClub,idResource,permission,password,comments) Values( '012','GILLE L.','01','H017','1','toto','')
insert into [USER] (id,name,idClub,idResource,permission,password,comments) Values( '013','JOKE M.','01','H009','1','toto','')
insert into [USER] (id,name,idClub,idResource,permission,password,comments) Values( '014','PIXEL F.','01','H021','1','toto','')
insert into [USER] (id,name,idClub,idResource,permission,password,comments) Values( '015','STONE K.','01','H011','1','toto','')
insert into [USER] (id,name,idClub,idResource,permission,password,comments) Values( '020','FOREST M.','02','H014','2','toto','Responsable administratif et financier')
insert into [USER] (id,name,idClub,idResource,permission,password,comments) Values( '021','DUNAND A.','02','H013','1','toto','')
insert into [USER] (id,name,idClub,idResource,permission,password,comments) Values( '030','AGENT M.','03','H001','2','toto','')
insert into [USER] (id,name,idClub,idResource,permission,password,comments) Values( '031','ANGEL D.','03','H002','0','toto','')
insert into [USER] (id,name,idClub,idResource,permission,password,comments) Values( '032','COULOIR R.','03','H010','0','toto','')
insert into [USER] (id,name,idClub,idResource,permission,password,comments) Values( '033','DEMAIN L.','03','H012','0','toto','')
insert into [USER] (id,name,idClub,idResource,permission,password,comments) Values( '034','FRANCOIS A.','03','H015','0','toto','')
insert into [USER] (id,name,idClub,idResource,permission,password,comments) Values( '035','FREEMAN T.','03','H030','0','toto','')
insert into [USER] (id,name,idClub,idResource,permission,password,comments) Values( '036','GREATMAN A.','03','H003','0','toto','')
insert into [USER] (id,name,idClub,idResource,permission,password,comments) Values( '037','HERO Y.','03','H004','2','toto','')
insert into [USER] (id,name,idClub,idResource,permission,password,comments) Values( '038','HOPE W.','03','H005','0','toto','')
insert into [USER] (id,name,idClub,idResource,permission,password,comments) Values( '039','HUNTER J.','03','H028','0','toto','')
insert into [USER] (id,name,idClub,idResource,permission,password,comments) Values( '03A','LION A.','03','H029','0','toto','')
insert into [USER] (id,name,idClub,idResource,permission,password,comments) Values( '03B','LONGWAY J.','03','H018','0','toto','')
insert into [USER] (id,name,idClub,idResource,permission,password,comments) Values( '03C','MARS L.','03','H019','0','toto','')
insert into [USER] (id,name,idClub,idResource,permission,password,comments) Values( '03D','PAUL J.','03','H020','0','toto','')
insert into [USER] (id,name,idClub,idResource,permission,password,comments) Values( '03E','ROBOT C.','03','H023','0','toto','')
insert into [USER] (id,name,idClub,idResource,permission,password,comments) Values( '03F','ROSE B.','03','H024','0','toto','')
insert into [USER] (id,name,idClub,idResource,permission,password,comments) Values( '03G','SAINT J.','03','H025','0','toto','')
insert into [USER] (id,name,idClub,idResource,permission,password,comments) Values( '03H','THIEBAT G.','03','H026','0','toto','')
insert into [USER] (id,name,idClub,idResource,permission,password,comments) Values( '03I','VILLE G.','03','H027','0','toto','')
insert into [USER] (id,name,idClub,idResource,permission,password,comments) Values( '03J','ANONYMOUS F.','03','H031','0','toto','')
insert into [USER] (id,name,idClub,idResource,permission,password,comments) Values( '040','SUPERMAN J.','04','H007','2','','')
insert into [USER] (id,name,idClub,idResource,permission,password,comments) Values( '041','FOREST M.','04','H014','1','','')
